import { Booth } from "../interface/Booth";
type BoothType = Booth & {
  members: string[];
  booth_id: string;
  s3_path: string;
  logo: string;
  mainColor: string;
};

export const boothsData: BoothType[] = [
  {
    name: "누토",
    type: ["웹사이트", "앱"],
    img: "/images/booths/nutoIntroduce.svg",
    developer: ["오지은", "이소리", "장하영"],
    designer: ["조혜원", "박새봄"],
    comment:
      "이번 프로젝트는 졸업 전시를 더욱 특별하게 기록하고, 학생들의 배움과 성장을 관객들과 소통할 수 있도록 기획되었습니다. 각 부스에는 학생들의 열정과 창의성이 담겨 있으며, 이를 응원하고 기억할 수 있도록 디지털 응원 메시지 시스템을 도입했습니다. 🔗 QR 코드로 간편하게 접속하여, 각 부스를 둘러보고 응원의 한마디를 남길 수 있습니다. 🍅 '토마토 텃밭'이라는 컨셉을 활용해, 한 마디 한 마디가 씨앗이 되어 성장하는 의미를 담았습니다. 관람객들은 학생들에게 따뜻한 격려를 전하고, 남겨진 메시지는 마치 정성껏 가꾼 텃밭처럼 쌓여갑니다.",
    members: ["오지은", "이소리", "장하영", "조혜원", "박새봄"],
    booth_id: "nuto",
    s3_path: "nuto",
    logo: "/images/boothName.svg",
    mainColor: "#C5362E",
  },
  {
    name: "미림취뽀",
    type: ["게임"],
    img: "/images/booths/미림취뽀.png",
    developer: ["최여은", "이민서"],
    designer: ["김민서", "박서정"],
    comment:
      "[미림취뽀]는 미림마이스터고 학생들이 학교에 입학하고 나서 취업까지 성공하는 루트를 게임으로 재미있게 풀어냈습니다. 취업을 하는 과정이 쉽지는 않지만 그럼에도 학생들이 끊임없이 도전하고 성장해 나가는 모습을 게임 속 여정에 녹여냈습니다.",
    members: ["최여은", "이민서", "김민서", "박서정"],
    booth_id: "미림취뽀",
    s3_path: "미림취뽀",
    logo: "/images/boothName.svg",
    mainColor: "#C5362E",
  },
  {
    name: "미림마법고민해결",
    type: ["웹사이트"],
    img: "/images/booths/미림마법고민해결.png",
    developer: ["김이레", "한지연", "윤성연", "이세현", "송민채"],
    designer: ["박솔하"],
    comment:
      "선생님의 목소리를 닮은 AI가 담긴 마법의 수정구슬 . 고민을 말하면 조용히 듣고, 차분하고 따뜻한 조언을 건넵니다. 진로, 인간관계, 감정 등 다양한 고민을 함께 나눌 수 있어요. 언제든 꺼내어 대화할 수 있는 나만의 작은 상담 도구입니다. 혼자일 때도, 이 구슬은 당신의 이야기를 기다리고 있어요.",
    members: ["김이레", "한지연", "윤성연", "이세현", "송민채", "박솔하"],
    booth_id: "미림마법고민해결",
    s3_path: "미림마법고민해결",
    logo: "/images/boothName.svg",
    mainColor: "#C5362E",
  },
  {
    name: "Soft Whisper",
    type: ["웹사이트"],
    img: "/images/booths/softwhisper.jpg",
    developer: ["김서연", "이서윤"],
    designer: ["김서연", "이서윤"],
    comment:
      "다양한 운세를 만나볼 수 있으며, 애니메이션과 함께 오늘의 운세를 즐길 수 있습니다. 마음에 드는 운세는 이메일로 공유할 수 있어 소중한 기억으로 간직할 수 있습니다. 당신의 하루를 특별하게 만들어 줄 경험이 기다리고 있습니다.",
    members: ["김서연", "이서윤"],
    booth_id: "softwhisper",
    s3_path: "softwhisper",
    logo: "/images/boothName.svg",
    mainColor: "#C5362E",
  },
  {
    name: "Ozmate",
    type: ["앱"],
    img: "/images/booths/ozmate.png",
    developer: ["배주연"],
    designer: ["윤한설"],
    comment:
      "이 앱은 호주 이민자들을 위한 정보 플랫폼입니다. 비자 정보, 현지 생활 팁, 환율 계산기, 날씨 확인, 챗봇 상담, 영어 해석 연습, 문화 퀴즈 등 실질적으로 필요한 기능을 한곳에 통합하여,사용자가 앱 하나만으로도 정보 탐색, 학습, 실생활 활용까지 가능하도록 다양한 기능을 담았습니다.",
    members: ["배주연", "윤한설"],
    booth_id: "ozmate",
    s3_path: "ozmate",
    logo: "/images/logos/ozmate.png",
    mainColor: "#FFF9C4",
  },
  {
    name: "워클리",
    type: ["웹"],
    img: "/images/booths/워클리.png",
    developer: ["배주연", "박수민", "이성미"],
    designer: ["양현서"],
    comment:
      "일정관리, 게시판, 직무별 팁을 제공합니다. 사회초년생에게 필요한 단어와 팁을 알려주고, 게시판 질문으로 회사 생활을 돕습니다. 사회초년생들이 회사에 잘 적응하도록 지원합니다.",
    members: ["배주연", "박수민", "이성미", "양현서"],
    booth_id: "workly",
    s3_path: "workly",
    logo: "/images/boothName.svg",
    mainColor: "#3B44E6",
  },
  {
    name: "InterYou",
    type: ["웹"],
    img: "/images/booths/interyou.png",
    developer: ["전유림", "육준성", "신채은", "조현진", "정다운", "이상희"],
    designer: ["전유림"],
    comment:
      "InterYou는 즉흥적인 면접 상황을 연습하고, AI 기반 분석으로 자신의 답변을 평가하기 위해 만들어졌습니다. InterYou를 통해 순발력과 사고력을 키우고, 실전 인터뷰 대응 능력을 강화할 수 있습니다. 창의적인 질문이 주어지면, 제한 시간 동안 생각하고 답변합니다. AI는 논리성과 창의성을 기준으로 답변을 평가합니다. 랭킹 기능을 제공하여 사용자 간 경쟁과 성장을 유도합니다.당신에게 질문합니다, InterYou 🎤",
    members: ["전유림", "육준성", "신채은", "조현진", "정다운", "이상희"],
    booth_id: "interyou",
    s3_path: "interyou",
    logo: "/images/boothName.svg",
    mainColor: "#B3CBFF",
  },
  {
    name: "미림페이",
    type: ["앱", "키오스크"],
    img: "/images/booths/미림페이.png",
    developer: ["지수민", "유성윤", "이효은", "강재호"],
    designer: ["송지아", "이서현"],
    comment:
      "MIRIM PAY는 교내 매점 무인 결제 시스템 및 통합 모바일 서비스입니다. 지갑을 두고 와 결제를 하지 못했던 경험이나 매점에 원하는 물품이 없어 발길을 돌렸던 순간처럼, 학생들이 일상 속에서 겪는 작지만 반복되는 불편함을 해결하고자 MIRIM PAY를 만들게 되었습니다. 복잡한 절차 없이 학교 이메일로 간편하게 로그인하고 개인 카드를 앱에서 등록한다면, QR 코드 스캔 또는 얼굴 인식만으로 지갑 없이도 즉시 안전하고 간편하게 결제할 수 있습니다. 또한 MIRIM PAY는 단순히 결제 도구를 제공할 뿐만 아니라 앱 내에서 매점의 실시간 재고를 확인하고, 필요한 문의 사항도 간편하게 전달할 수 있는 기능을 제공해 학생들의 매점 이용을 한층 더 편리하고 유연하게 만들어 줍니다. MIRIM PAY를 통해 보다 편리하고 효율적으로 매점을 이용할 수 있습니다!",
    members: ["지수민", "유성윤", "이효은", "강재호", "송지아", "이서현"],
    booth_id: "mirimpay",
    s3_path: "mirimpay",
    logo: "/images/boothName.svg",
    mainColor: "",
  },
  {
    name: "Dearpal",
    type: ["웹"],
    img: "/images/booths/dearpal.png",
    developer: ["최여은"],
    designer: ["최여은"],
    comment:
      "회원가입 후, 사용자끼리 익명의 사용자끼리 서로 편지를 주고받을 수 있는 웹 플랫폼입니다. 편지는 사용자가 직접 선택해서 확인하고 답장할 수 있으며, 텍스트와 스티커를 활용해 편지를 꾸밀 수 있는 기능도 포함되어 있습니다. 가입부터 편지 작성, 교류까지 간단한 플로우로 누구나 쉽게 사용할 수 있습니다.",
    members: ["최여은"],
    booth_id: "dearpal",
    s3_path: "dearpal",
    logo: "/images/boothName.svg",
    mainColor: "",
  },
  {
    name: "Harugo",
    type: ["앱"],
    img: "/images/booths/harugo.png",
    developer: ["이성미", "정민경"],
    designer: ["서유미"],
    comment:
      "상황에 맞는 표현을 배우고 퀴즈를 통해 다양한 포코로를 획득해 도감을 완성하며 재미를 느낄 수 있습니다.",
    members: ["이성미", "정민경", "서유미"],
    booth_id: "harugo",
    s3_path: "harugo",
    logo: "/images/logos/harugo.png",
    mainColor: "#FD7033",
  },
  {
    name: "짤메이커",
    type: ["웹"],
    img: "/images/booths/짤메이커.png",
    developer: ["박가빈"],
    designer: ["박가빈"],
    comment:
      "인스타, 유튜브 쇼츠에서 쉽게 접할 수 있는 컨텐츠인 짤을  나도 쉽게 만들 수 있다면 어떨까요?  자신이 평소 좋아하던 캐릭터나 재밌는 사진에  말풍선과 자막을 추가해서 생동감을 더할 수 있는 사이트를 만들고 싶었습니다. 그렇게 기획한 짤메이커는 짤을 만들기 위한 편집 기능과 템플릿을 제공하는 웹서비스입니다. 자신이 가지고 있는 사진을 업로드하거나 제공된 템플릿을 선택하고 말풍선이나 자막을 추가해서 짤을 만들 수 있습니다. 완성된 짤로 여러 SNS에서 활용할 수 있습니다.",
    members: ["박가빈"],
    booth_id: "zzalmaker",
    s3_path: "zzalmaker",
    logo: "/images/logos/짤메이커.png",
    mainColor: "#A8B1DA",
  },
  {
    name: "Q&A",
    type: ["앱"],
    img: "/images/booths/q&a.png",
    developer: ["김리연", "박가빈", "채연우"],
    designer: ["이영서"],
    comment:
      "Q&A는 선생님과 학생의 1:1 질문, 일정 공유, 개인 프로필 관리 기능 등을 제공합니다.  대면이 어려운 상황에서 학생과 선생님의 원활한 소통을 도와 학생은 궁금한 점을 질문하고, 개인 일정을 관리를 할 수 있습니다.이 앱을 기획한 의도는 학교 생활 동안 너무나 많이 쏟아지는  질문들을 대면 없이 하고 싶어서 설계 했습니다.  뿐만 아니라 캘린더, 개인 프로필 관리 기능으로 학교 생활에  필요한 스케쥴링을 효율적으로 할 수 있습니다.",
    members: ["김리연", "박가빈", "채연우", "이영서"],
    booth_id: "q&a",
    s3_path: "q&a",
    logo: "/images/logos/q&a.png",
    mainColor: "#F2AA9C",
  },
  {
    name: "Migwarts",
    type: ["웹"],
    img: "/images/booths/migwarts.png",
    developer: ["이소리", "정상미", "김호정", "배주연"],
    designer: ["박가빈"],
    comment:
      "영화 해리포터 세계관을 바탕으로 자신의 기숙사와, 캐릭터 테스트를 할 수 있는 웹사이트 입니다. 학번과 이름을 입력 한 후 기숙사와 캐릭터 테스트를 하고 결과를 본 후 그 기숙사와 캐릭터에 맞는 사람들과 채팅을 할 수 있습니다. 자신의 기숙사와 캐릭터를 알아보세요!",
    members: ["박가빈"],
    booth_id: "migwarts",
    s3_path: "migwarts",
    logo: "/images/logos/migwarts.png",
    mainColor: "#4C1E1E",
  },
  {
    name: "Interactive",
    type: ["게임"],
    img: "/images/booths/interactive.png",
    developer: ["양은서", "이서영", "안채연", "윤주영", "심정민", "구아연"],
    designer: ["양은서"],
    comment:
      "여자어게임은 일상 속에서 자주 사용되지만 남성들이 쉽게 이해하지 못하는 여성들만의 표현, 말투, 줄임말, 또는 뉘앙스가 담긴 언어들을 퀴즈 형식으로 재미있게 풀어보는 웹 기반 게임입니다. 단순한 언어 맞히기를 넘어, 성별 간의 사고방식 차이나 표현 방식의 다양성에 대한 이해를 넓힐 수 있도록 구성되어 있으며, 친구나 연인끼리 함께 플레이하며 서로의 관점을 알아가고 소통하는 데에도 유용한 요소들을 담고 있는 콘텐츠입니다. ",
    members: [
      "양은서",
      "이서영",
      "안채연",
      "윤주영",
      "심정민",
      "구아연",
      "양은서",
    ],
    booth_id: "interactive",
    s3_path: "interactive",
    logo: "/images/logos/interactive.png",
    mainColor: "#E10CA1",
  },
  {
    name: "Journimal",
    type: ["앱"],
    img: "/images/booths/journimal.png",
    developer: ["김지혜", "추다율"],
    designer: ["탁경민"],
    comment:
      "사용자는 여행 중 실천할 수 있는 다양한 환경 보호 미션을 직접 선택하고, 여행을 함께할 멸종위기 동물 친구들을 만납니다. 여행이 끝나면, 여행이 기록된 특별한 티켓을 받습니다. Let’s travel, Let’s protect, Let’s Journimal!",
    members: ["김지혜", "추다율", "탁경민"],
    booth_id: "journimal",
    s3_path: "journimal",
    logo: "/images/logos/journimal.png",
    mainColor: "#022169",
  },
  {
    name: "Momenpick",
    type: ["웹"],
    img: "/images/booths/momenpick.png",
    developer: ["김지혜", "박지영"],
    designer: ["이자연", "정세연"],
    comment:
      "고등학교 시절은 단 한 번뿐인 특별한 시간입니다. 학창시절의 모든 순간을 간직할 수 있도록 누구나 쉽게 사용할 수 있는 추억이 담긴 셀프 사진 촬영 서비스를 기획했습니다. 사용자가 직접 원하는 분위기와 테마를 선택하고, 자동 촬영으로 편하게 사진을 남겨 소중한 사람들과 추억을 기록할 수 있도록 구성했습니다. 단순한 사진 한 장을 넘어서, 공감과 감성 그리고 유대감을 담는 경험을 제공하고자 합니다.",
    members: ["김지혜", "박지영", "이자연", "정세연"],
    booth_id: "momenpick",
    s3_path: "momenpick",
    logo: "/images/logos/momenpick.png",
    mainColor: "#714946",
  },
  {
    name: "밥밥밥",
    type: ["앱"],
    img: "/images/booths/babbabbab.png",
    developer: ["김지혜", "백지현", "양혜원", "정상미"],
    designer: ["하지민"],
    comment:
      "밥밥밥 서비스는 중고등학생들의 자발적인 환경 보호 실천을 독려하고, 급식을 통해 일상 속에서 친환경 활동을 실천할 수 있도록 돕는 플랫폼을 소개하고자 마련되었습니다. 지금 우리는 심각한 환경 위기의 시대에 살고 있습니다. 기후 변화, 플라스틱 오염, 식량 낭비 등 다양한 환경 문제가 점점 심화되고 있는 현실 속에서, 우리 청소년들이 일상에서 환경을 위해 할 수 있는 일은 무엇일까요? 저희는 그 해답을 '급식'에서 찾았습니다. 부스에서는 학생들이 스마트폰으로 학교 급식 사진을 업로드하고, 이를 통해 개인 뱃지를 수집하는 시스템을 체험할 수 있습니다. 뱃지는 일정한 조건을 달성하면 주어지며, 이를 통해 성취감을 느끼고 지속적인 참여를 유도합니다. 뿐만 아니라, 랭킹 시스템을 통해 친구들과의 선의의 경쟁을 즐길 수 있고, 급식을 통해 학교의 식단 구성과 음식물 쓰레기 배출량을 점검하며 환경 보호의식을 높이는 계기가 됩니다. 또한, 부스에서는 다양한 환경 관련 이슈와 급식 속의 환경 정보도 제공하여, 단순한 사진 업로드를 넘어서 환경 교육의 장이 될 수 있도록 구성하였습니다. 음식물 쓰레기를 줄이는 법, 지속 가능한 식습관, 친환경 식재료에 대한 정보 등 실생활과 밀접한 이야기들이 여러분을 기다리고 있습니다. 저희는 학생들이 '환경 보호는 거창하지 않아도 된다'는 메시지를 느끼고, 작은 실천 하나하나가 세상을 바꾸는 시작이 될 수 있다는 사실을 경험하길 바랍니다. 급식을 통해 나의 실천을 기록하고, 친구들과 함께 목표를 이루며, 즐겁게 환경 보호에 동참할 수 있는 이 부스에서 여러분의 참여를 기다립니다! 환경은 멀리 있지 않습니다. 여러분의 점심 식판 위에서도, 일상의 선택 속에서도, 그리고 바로 이 부스에서부터 시작됩니다.지금, 여기서 밥밥밥과 함께 시작해볼까요? ",
    members: ["김지혜", "백지현", "양혜원", "정상미", "하지민"],
    booth_id: "babbabbab",
    s3_path: "babbabbab",
    logo: "/images/logos/babbabbab.png",
    mainColor: "#FFAD0A",
  },
  {
    name: "CAREER TEEN",
    type: ["웹"],
    img: "/images/booths/careerteen.png",
    developer: ["박지영", "박수민"],
    designer: ["이자연"],
    comment:
      "취업을 원하는 직업계고 학생들과진학을 원하는 고등학교 졸업생을 위한 멘토링으로 관련 종사자에게 조언을 듣고스터디그룹이나 게시판을 통해 정보를 공유하는 서비스입니다.",
    members: ["박지영", "박수민", "이자연"],
    booth_id: "careerteen",
    s3_path: "careerteen",
    logo: "/images/logos/careerteen.png",
    mainColor: "#714946",
  },
  {
    name: "미림 마법 고민 해결",
    type: ["웹"],
    img: "/images/booths/미림마법고민해결.png",
    developer: ["김이레", "한지연", "윤성연", "이세현", "송민채"],
    designer: ["박솔하"],
    comment:
      "선생님의 목소리를 닮은 AI가 담긴 마법의 수정구슬. 고민을 말하면 조용히 듣고, 차분하고 따뜻한 조언을 건넵니다. 진로, 인간관계, 감정 등 다양한 고민을 함께 나눌 수 있어요. 언제든 꺼내어 대화할 수 있는 나만의 작은 상담 도구입니다. 혼자일 때도, 이 구슬은 당신의 이야기를 기다리고 있어요.",
    members: ["김이레", "한지연", "윤성연", "이세현", "송민채", "박솔하"],
    booth_id: "미림마법고민해결",
    s3_path: "미림마법고민해결",
    logo: "/images/logos/미림마법고민해결.png",
    mainColor: "#AF88F0",
  },
  {
    name: "오늘도 잘먹었습니다",
    type: ["앱"],
    img: "/images/booths/오잘먹.png",
    developer: ["이서영", "박지영"],
    designer: ["박세연", "박새봄"],
    comment:
      "요리를 잘 알지 못하거나 자취 생활을 하다 보면, 적은 식재료로 어떤 요리를 해야 할지 막막할 때가 많습니다. 많은 재료를 모두 갖추지 못한 상황에서는 재료를 버리게 되는 일도 잦고, 이는 요리에 대한 부담으로 이어지기도 합니다. 이 앱은 냉장고 속 재료를 기반으로 만들 수 있는 요리를 추천하고, 나만의 레시피를 기록하고 공유할 수 있는 기능을 제공합니다. 음식물 낭비를 줄이고 식비를 절약하며, 건강한 식습관을 형성하는 데 도움이 되도록 기획하였습니다.",
    members: ["이서영", "박지영", "박세연", "박새봄"],
    booth_id: "오잘먹",
    s3_path: "오잘먹",
    logo: "/images/logos/오잘먹.png",
    mainColor: "#AAAE32",
  },
  {
    name: "Chuu",
    type: ["웹"],
    img: "/images/booths/chuu.png",
    developer: ["오지은", "안효주", "조수빈"],
    designer: ["하지민"],
    comment:
      "나의 미림 선생님 추구미를 알아보는 웹 서비스입니다. 미림 선생님 추구미 테스트와 AI 채팅, 프레임 사진 촬영 기능을 제공합니다. 선생님을 대상으로 나의 성격 유형을 알아보고, 존경하는 선생님과의 사진 촬영을 통해 특별한 추억을 만들 수 있습니다. 항상 감사한 선생님들과의 추억을 남길 수 있는 전시가 되길 바라는 마음으로 기획하였습니다.",
    members: ["오지은", "안효주", "조수빈", "하지민"],
    booth_id: "chuu",
    s3_path: "chuu",
    logo: "/images/logos/chuu.png",
    mainColor: "#65E9FF",
  },
  {
    name: "Automat",
    type: ["웹"],
    img: "/images/booths/automat.png",
    developer: ["백지현", "안효주", "조수빈"],
    designer: ["하지민"],
    comment:
      "사진을 찍어 나만의 음악 앨범을 만드는 서비스입니다. 사진을 찍어 사진 속 다양한 감정, 상황들을 분석해 어울리는 음악을 생성합니다. 그 후 다양한 표정을 지으며 실시간으로 펜의 색상을 바꿔가며 직접 앨범 표지를 그려 나만의 개성 있는 음악 앨범을 만들고 꾸밀 수 있습니다. 전시를 관람하며 각자의 시선으로 느낀 분위기와 감정을 음악과 시각 요소로 표현하여 보다 개성 있는 특별한 형태로 감정을 기록하고 공유할 수 있도록 하였습니다. 단순한 감상에 머무르지 않고, 나의 감정을 창작으로 연결해보는 감성적인 표현의 장이 되길 바라는 마음에서 이 프로젝트를 기획하게 되었습니다.",
    members: ["백지현", "안효주", "조수빈", "하지민"],
    booth_id: "automat",
    s3_path: "automat",
    logo: "/images/logos/automat.png",
    mainColor: "#00A4C8",
  },
  {
    name: "Don't say that",
    type: ["게임"],
    img: "/images/booths/dontsaythat.png",
    developer: ["추다율", "양혜원"],
    designer: ["추다율", "양혜원"],
    comment:
      "금칙어를 피해 대화하는 실시간 멀티플레이 게임입니다. 방 생성, 대기방, 금칙어 설정, 랭킹 등의 기능으로, 친구들과 함께 실시간으로 즐길 수 있습니다. 짧은 쉬는 시간에도 친구들과 부담 없이 즐길 수 있는, 금칙어를 피해 대화하는 실시간 멀티플레이 게임입니다. 복잡한 규칙 없이도 간단한 조작만으로 즐길 수 있도록 기획하였습니다.",
    members: ["추다율", "양혜원"],
    booth_id: "dontsaythat",
    s3_path: "dontsaythat",
    logo: "/images/logos/dontsaythat.png",
    mainColor: "#F8AE01",
  },
  {
    name: "WePick",
    type: ["웹"],
    img: "/images/booths/wepick.png",
    developer: ["김가현", "나지수", "정상미", "추다율"],
    designer: ["김예린", "조혜원"],
    comment:
      "찍었던 사진들을 언제, 어디서 찍었는지 오래 추억하고 싶은 사람들을 위해 WePick을 만들게 되었습니다. 간직하고 싶은 네컷 사진을 업로드하고 기억하고 싶은 사진관의 위치를 지도에 남길 수 있습니다. 그날의 일들을 일기로 기록하여 업로드한 사진과 추억을 카테고리별로 모아  📸여러분의 소중한 추억을 WePick으로 정리해보세요😉",
    members: ["김가현", "나지수", "정상미", "추다율", "김예린", "조혜원"],
    booth_id: "wepick",
    s3_path: "wepick",
    logo: "/images/logos/wepick.png",
    mainColor: "#939393",
  },
];
