name: Deploy Frontend to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout Repo
        uses: actions/checkout@v3

      - name: 🛠 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install deps
        run: npm install

      - name: 🏗 Build frontend
        run: CI=false npm run build

      - name: 🐳 Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_IMAGE_NAME }} .

      - name: 📦 Save Docker image to tar
        run: docker save -o nuto-frontend.tar ${{ secrets.DOCKER_IMAGE_NAME }}

      - name: 🔐 Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: 📡 Upload .tar to EC2
        run: scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no nuto-frontend.tar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/nuto-frontend.tar

      - name: 🚀 Deploy on EC2
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            sudo docker stop nuto-frontend || true
            sudo docker rm nuto-frontend || true
            sudo docker rmi ${{ secrets.DOCKER_IMAGE_NAME }} || true
            sudo docker load -i /home/ubuntu/nuto-frontend.tar
            sudo docker run -d -p 80:80 --name nuto-frontend ${{ secrets.DOCKER_IMAGE_NAME }}
          EOF
