name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/nuto-frontend .

    - name: Save Docker image as tar
      run: |
        docker save -o nuto-frontend.tar ${{ secrets.DOCKER_USERNAME }}/nuto-frontend

    - name: Create PEM key file
      run: |
        echo "${{ secrets.EC2_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Copy tar to EC2
      run: |
        scp -i key.pem -o StrictHostKeyChecking=no nuto-frontend.tar ubuntu@${{ secrets.EC2_HOST }}:~/

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          sudo docker load -i nuto-frontend.tar
          cd ~/your-backend-folder  # docker-compose 있는 곳
          docker-compose up -d
