name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/nuto-frontend:latest .

    - name: Save Docker image as tar
      run: |
        docker save -o nuto-frontend.tar ${{ secrets.DOCKER_USERNAME }}/nuto-frontend:latest

    - name: Create PEM key file
      run: |
        echo "${{ secrets.EC2_KEY_BS64 }}" | tr -d '\n' | base64 -d > key.pem
        chmod 600 key.pem

    - name: Copy tar to EC2
      run: |
        rsync -avz -e "ssh -i key.pem -o StrictHostKeyChecking=no" nuto-frontend.tar ubuntu@${{ secrets.EC2_IP }}:~/
    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          sudo apt-get update
          sudo apt-get install docker-compose  
          sudo docker load -i nuto-frontend.tar
          cd ~/nuto-backend
          docker stop nuto-frontend
          docker rm nuto-frontend
          docker-compose up -d
