name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        run: echo "${{ secrets.GIT_ENV }}" > .env
        
      - name: Create PEM key file
        run: |
          echo "${{ secrets.EC2_KEY_BS64 }}" | tr -d '\n' | base64 -d > key.pem
          chmod 600 key.pem

      - name: Docker image build & push
        working-directory: ${{ github.workspace }}
        run: |
          docker build -t nuto-frontend .
          docker tag nuto-frontend ${{ secrets.DOCKER_USERNAME }}/nuto-frontend:latest
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/nuto-frontend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/nuto-frontend:latest
            cd ~/nuto-frontend || { echo "폴더가 없습니다. Docker 이미지만 pull해도 됩니다."; exit 0; }
            docker-compose down || echo "docker-compose down 실패";
            docker-compose up -d || echo "docker-compose up 실패";
