name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Create PEM key file
        run: |
          echo "${{ secrets.EC2_KEY_BS64 }}" | tr -d '\n' | base64 -d > key.pem
          chmod 600 key.pem

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            # DockerHub에서 프론트엔드 이미지 pull
            docker pull jieuniaeyo/nuto-frontend:latest
            
            # 기존 컨테이너 종료 및 새로 시작
            cd ~/nuto-frontend
            docker-compose down
            docker-compose up -d
